### ISSUE TITLE
CIMI sensor resource definition

### ISSUE THREAD

**Issue by sstanovnik** [mF2C/cimi#53]
The sensor manager requires a CIMI resource that lists categorised sensors. See mF2C/mF2C#115 for my thoughts on what should be included.

**Comment by ssgUPC** [comment]
Will definitely change the CIMI resource scheme, when the automatic sensor categorization module will be ready.

**Comment by sstanovnik** [comment]
Can we at least agree on the fields this resource will have in advance? It would help me get at least a general interface going. 

What I would like it to contain:
* hardware identifier (e.g. am2032, bmp180)
* a list of SI dimensions each hardware identifier provides (e.g. ["temperature", "humidity"] for am2302)
* connection parameters: not the protocol the hardware is connected through (this is determined by the hardware type), but the details of the connection, e.g. "GPIO12" for am2302, which is a single-data-wire sensor

**Comment by ssgUPC** [comment]
Yes, I also agree with you that, if we agree on the fields, it would really good for both of us. But dear, I think it would be great if we make a short telco....and then fix the list of fields, what do you think?? By the way, just for your information, tomorrow I'll be not available and Monday also, so if you want we can discuss it after Monday...

**Comment by sstanovnik** [comment]
I'd much prefer a Slack chat, if that's okay with you, so we get the added benefit of having notes right there. Is Tuesday okay? I'll just ping you then.

**Comment by sstanovnik** [comment]
To summarise online offline discussions we've had between our teams: this will be done by creating a simple interface to all of the values, hardcoded. This will allow further development on both sides to progress independently.

**Comment by ssgUPC** [comment]
mF2C/cimi#56 Added the sensor information in CIMI resource (schema)

**Comment by sstanovnik** [comment]
Blocked by #57.

**Comment by sstanovnik** [comment]
Finalised through #57.
