### ISSUE TITLE
Modify CIMI resource schema for device-dynamic

### ISSUE THREAD

**Issue by ssgUPC** [mF2C/cimi#58]
Need to change the CIMI resource schema for device-dynamic

**Comment by aqueralt** [comment]
Hi Souvik, does this mean that the device-dynamic spec is not yet ready? Yesterday I understood that it was done, so I am not sure whether we need to wait for an update or not

**Comment by ssgUPC** [comment]
Hi, @aqueralt though I have already added the `sensor` information to the `device-dynamic`, still it needs to be changed and modified a bit...So that means it is not yet ready...and will take some time to change it correctly... But, whenever it will finish, I'll definitely let you know.

**Comment by ssgUPC** [comment]
@aqueralt I have already modified the CIMI resource schema for the `device` and `device-dynamic`, so can you please send me the link of corresponding dc class files. So, that I can start modifying it also.

**Comment by aqueralt** [comment]
Hi Souvik, don't worry, we'll do it.

**Comment by ssgUPC** [comment]
@aqueralt thanks a lot!!!
