### ISSUE TITLE
500 creating an sla-violation

### ISSUE THREAD

**Issue by rosogon** [mF2C/cimi#67]
on dashboard.mf2c-project.eu. The response is:
```
{
  "status" : 500,
  "message" : "Unexpected exception thrown: java.io.ByteArrayInputStream cannot be cast to clojure.lang.IPersistentMap"
}
```

Using the following body:
```
{
    "agreement_id": { "href" : "agreement/880e82bf-32b7-4b7b-b89b-386d4c46310c" },
    "guarantee": "gt01",
    "datetime": "2018-01-16T17:09:45.001Z",
    "constraint": "responsetime < 1000",
    "values": {
        "responsetime": 2000
    },
    "acl": {
        "owner": { "principal": "ADMIN", "type": "ROLE" },
        "rules": [ { "type": "ROLE", "principal": "USER", "right": "MODIFY" } ]
    }
}
```

**Comment by cjdcordeiro** [comment]
from past experience this usually is an inconsistency between the cimi spec and DC data model. Can you 1) check you have equal schemas, and 2) that the right docker image tags are running in dashboard?

**Comment by aqueralt** [comment]
Ok, the error seems to be a mismatch in the field agreement_id, which should be a resource link but it is currently a string in the dataClay data model. Unfortunately we cannot solve it until next week, sorry.

**Comment by rosogon** [comment]
The actual message body is:
```
{
  "status" : 500,
  "message" : "unexpected error occurred: error executing request: [:add {:constraint \"responsetime < 1000\", :updated \"2019-04-15T09:48:26.253Z\", :created \"2019-04-15T09:48:26.253Z\", :guarantee \"gt01\", :id \"sla-violation/7143d12d-26a8-4f5b-89e2-10404b92f312\", :values {:responsetime 2000}, :datetime \"2018-01-16T17:09:45.001Z\", :acl {:owner {:principal \"ADMIN\", :type \"ROLE\"}, :rules [{:type \"ROLE\", :principal \"USER\", :right \"MODIFY\"}]}, :resourceURI \"http://schemas.dmtf.org/cimi/2/SlaViolation\", :agreement_id {:href \"agreement/880e82bf-32b7-4b7b-b89b-386d4c46310c\"}} {}]\njava.lang.ClassCastException: java.util.HashMap cannot be cast to java.lang.String"
}
```
`java.lang.ClassCastException: java.util.HashMap cannot be cast to java.lang.String`

I checked spec[[1]] and dc model[[2]] and them seem congruent. There have been some changes in the spec (not by me) in the last months, but I think they should not affect. So:
1) I expect they are equal
2) The models are stable since one year ago. 

It looks clear that the error is in the `values`field. 

[1]: https://github.com/mF2C/cimi/blob/master/server/src/com/sixsq/slipstream/ssclj/resources/spec/sla_violation.cljc
[2]: https://github.com/mF2C/dataClay/blob/master/cimi_dataclay/model/src/CIMI/SlaViolation.java

**Comment by rosogon** [comment]
@aqueralt : Should it be a Map<String, object> like in DeviceDynamic[[1]]?. I can prepare a PR for that, but you must test before accepting.

[1]: https://github.com/mF2C/dataClay/blob/master/cimi_dataclay/model/src/CIMI/DeviceDynamic.java#L66

**Comment by daniwhere** [comment]
PR https://github.com/mF2C/mF2C/pull/160 created with modified SlaViolation, please try with dataclay 2.14

**Comment by rosogon** [comment]
I confirm it is fixed.
