### ISSUE TITLE
Error 500 when adding service metrics

### ISSUE THREAD

**Issue by sandlbn** [mF2C/cimi#90]
Given this payload on the post call to service-container-metrics

``{"start_time": "2019-08-27T20:40:34.623882421Z", "container_id": "8e1d995355c5be1610ee291d21e7c1d8d9f79778e60b1c177804a9e6c5dd4eed", "device_id": "319c6d17_b377_4584_aeb1_60f329e6240a"}``

I'm getting:

``{u'status': 500, u'message': u'Unexpected exception thrown: java.io.ByteArrayInputStream cannot be cast to clojure.lang.IPersistentMap'} ``

It could be reproduced with landscaper mf2c/landscaper:0.6.10

**Comment by cjdcordeiro** [comment]
@sandlbn the error is most likely due to a missing header: `-H content-type:application/json`

Besides, your payload is also wrong. It should be `...device_id": {"href": "device/319c..."}`

With these two things, I can successfully post this resource through CIMI.

**Comment by cjdcordeiro** [comment]
@sandlbn can you confirm this was not a problem?

**Comment by sandlbn** [comment]
@cjdcordeiro Yes payload was wrong on Landscaper side. was fixed in version 0.6.11.
